3.7.0
YunoHost-Apps/monica_ynh pull request #58
Opened 2022-05-27 13:00 UTC by ericgaspar

## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2022-05-27 13:01 UTC, ericgaspar commented
!testme

2022-05-30 12:58 UTC, yalh76 requested changes

2022-05-30 12:58 UTC, yalh76 commented on scripts/install
> +	ynh_replace_string  --match_string="MOBILE_KEY" --replace_string="$mobile_key" --target_file="$final_path/.env"
Checksum for `$final_path/.env` should be recalculate

2022-05-30 12:58 UTC, yalh76 commented on scripts/_common.sh
> +pkg_dependencies="php-redis php${YNH_PHP_VERSION}-bcmath php${YNH_PHP_VERSION}-cli php${YNH_PHP_VERSION}-curl php${YNH_PHP_VERSION}-dom php${YNH_PHP_VERSION}-gd php${YNH_PHP_VERSION}-gmp php${YNH_PHP
Doing that php7.3-redis will be installed instead of php7.4-redis

2022-06-09 06:35 UTC, closed without merging